### ISSUE TITLE
"Selon quelle période" doesn't work properly

### ISSUE THREAD

**Issue by blirette** [cfrp-laval/analytics#16]
When you select "Dimanche" in the submenu "Jour de la semaine" of the section "Selon quelle période", the results should only display "Dimanche" (see screenshot). Am I wrong to say it should display like that?

![sshot](https://cloud.githubusercontent.com/assets/1894507/20985882/5a09f306-bc94-11e6-894e-5de3f61f2739.png)

**Comment by hspier** [comment]
That's a good question. I would say that in this context it should only display "Dimanche". In general my testing was that the three filters are used on top of the period selector (decade) rather than separated axis.

Generally speaking, is the intent of selecting the month, day or room is to further refined the period (decade) selector or is it to use as a separate axis like you did?

**Comment by blirette** [comment]
To me, it should only use and display the values of "Dimanche". Maybe it has already been discussed otherwise before...?

**Comment by hspier** [comment]
I will have only "Dimanche" displayed as I agree this is a problem, but just asking the expectation when you select "Dimanche" but did not select "Jour de la semaine" on any of the axis ?

**Comment by blirette** [comment]
It took me a while to understand that "Selon quelle période" is only used to display results. It has no impact on the queries. Therefore, it should be seen as a tool to pinpoint specific data used on the queries. Is that clearer? Am I wrong?

**Comment by hspier** [comment]
Yes so I will fix the issue you mention and keep the current behavior. Basically, it will do two jobs: pinpoint results AND filter the list of values when used as an axis. Right now it is only doing the first part.
