### ISSUE TITLE
Alignment of the first columns of the table

### ISSUE THREAD

**Issue by blirette** [cfrp-laval/analytics#18]
The two first rows seems horizontally misaligned, at least in Chrome / MacOS.
![image](https://cloud.githubusercontent.com/assets/1894507/21229944/5178477e-c2b1-11e6-8e41-4c25e5549d37.png)

**Comment by blirette** [comment]
@hspier Still happening as of now. Is it a possible commit conflict that @jamiefolsom would have done yesterday? 
![image](https://cloud.githubusercontent.com/assets/1894507/22251269/1d6df39e-e218-11e6-9a82-f3684f8bb836.png)

**Comment by jamiefolsom** [comment]
@hspier @blirette FYI, I don't believe any of my changes have been merged to the gh-pages branch of the cfrp-laval repository, which is where the staging instance originates, and where these screenshots were taken.

**Comment by hspier** [comment]
@blirette I've added the "fixed" label to mark the defect as fixed in the dev branch, but this label doesn't mean that it is pushed to staging yet. Basically once an issue is pushed to staging, I will close it here. "fixed" helps me track the defect that are completed on my side until I push those to staging once I have enough fixes ready.

**Comment by blirette** [comment]
All good then! Thanks for the detailed explanation! ;)
